spring:
  application:
    name: SpringSecurityFreeDemo
  security:
    user:
      name: ronald
      password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/civic_alert
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB

upload:
  path: ./uploads
